__defaults__(
    all=dict(
        resolve=parametrize(
            "callbacks-arize-phoenix",
            "default",
            "packs-arize-phoenix-query-engine",
            "readers-semanticscholar",
            "readers-papers",
            "tools-arxiv",
        )
    )
)
poetry_requirements(
    name="root",
)
