__defaults__(
    all=dict(
        resolve=parametrize(
            "readers-stripe-docs",
            "readers-asana",
            "callbacks-argilla",
            "callbacks-arize-phoenix",
            "default",
            "packs-arize-phoenix-query-engine",
            "packs-recursive-retriever",
            "readers-docugami",
            "readers-hatena-blog",
            "readers-imdb-review",
            "readers-papers",
            "readers-semanticscholar",
            "readers-web",
            "readers-whatsapp",
            "readers-zep",
            "tools-arxiv",
            "vector-stores-zep",
        )
    )
)
poetry_requirements(
    name="root",
)
