__defaults__(
    all=dict(
        resolve=parametrize(
            "default",
            "arize-phoenix-2",
            "arize-phoenix-3",
        )
    )
)
poetry_requirements(
    name="root",
)
