[GLOBAL]
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.mixed_interpreter_constraints",
    "pants.backend.python.typecheck.mypy",
]
pants_version = "2.19.0"
remote_cache_read = true
remote_cache_write = true
remote_instance_name = "main"
remote_store_address = "grpc://44.204.50.6:9092"

[black]
config = "./pyproject.toml"

[python]
interpreter_constraints = ["==3.10.*"]
enable_resolves = true
default_resolve = "default"

[python.resolves]
default = "3rdparty/python/default.lock"
legacy = "3rdparty/python/legacy.lock"
arize-phoenix-2 = "3rdparty/python/arize-phoenix-2.lock"
arize-phoenix-3 = "3rdparty/python/arize-phoenix-3.lock"

[python-infer]
ambiguity_resolution = "by_source_root"

[source]
marker_filenames = ["pyproject.toml"]
root_patterns = ["*tests", "/"]
