__defaults__(all=dict(resolve="llama-index-indices-managed-llama-cloud"))
python_sources()

poetry_requirements(
    name="poetry",
    module_mapping={"llamaindex-py-client": ["llama_index_client"]},
)
