__defaults__(all=dict(resolve="llama-index-readers-google"))
poetry_requirements(
    name="poetry",
    module_mapping={
        "google-api-python-client": ["googleapiclient"],
        "google-auth-oauthlib": ["google_auth_oauthlib"],
    },
)


