__defaults__(all=dict(resolve="llama-index-readers-agent-search"))
poetry_requirements(
    name="poetry",
)

python_requirements(
    name="reqs",
)

python_sources(
    interpreter_constraints=["==3.9.*", "==3.10.*"],
)
