__defaults__(all=dict(resolve="llama-index-llms-gemini"))
poetry_requirements(name="poetry", module_mapping={"google-generativeai": ["google"]})

python_sources(
    interpreter_constraints=["==3.9.*", "==3.10.*"],
)
