__defaults__(all=dict(resolve="llama-index-llms-vertex"))
poetry_requirements(
    name="poetry", module_mapping={"google-cloud-aiplatform": ["vertexai"]}
)

python_sources(
    interpreter_constraints=["==3.9.*", "==3.10.*"],
)
